[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo  = 'scrooloose/nerdtree'

[[plugins]]
repo  =  'fholgado/minibufexpl.vim'

[[plugins]]
repo  =  'leafgarland/typescript-vim'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'thosakwe/vim-flutter'
